### ISSUE TITLE
Is the service down?

### ISSUE THREAD

**Issue by bsapwindows** [0x263b/Otherside#2]
First of all, thanks for making this!

I got `An unhandled lowlevel error occurred. The application logs may have details.` when I try to sign in with twitter today.

**Comment by 0x263b** [comment]
This is the issue I'm experiencing right now https://github.com/arunagw/omniauth-twitter/issues/131#issuecomment-399753979

Hopefully I get a response from Twitter support soon and get this sorted.

**Comment by 0x263b** [comment]
Should be fixed now
